import type { LiteraturePaper } from "./types";

// Demo-only records for the Literature UI milestone. No external API is called.
export const MOCK_LITERATURE_PAPERS: LiteraturePaper[] = [
  {
    id: "demo-blockchain-agriculture-2024",
    title: "Blockchain technology for sustainable agricultural supply chains",
    authors: ["M. Casino", "T. K. Dasaklis", "C. Patsakis"],
    year: 2024,
    source: "Demo catalog",
    publicationType: "Journal article",
    abstract: "A review of how distributed ledgers improve traceability, trust, and coordination across agricultural supply chains.",
    doi: "10.1016/j.techsoc.2024.102345",
    url: "https://doi.org/10.1016/j.techsoc.2024.102345",
  },
  {
    id: "demo-smart-farming-2023",
    title: "Smart farming and data transparency: A systematic review",
    authors: ["A. Walter", "R. Finger", "R. Huber"],
    year: 2023,
    source: "Demo catalog",
    publicationType: "Review article",
    abstract: "This systematic review examines data-sharing practices and transparency challenges in digitally enabled agriculture.",
    doi: "10.1007/s13593-023-00912-8",
  },
  {
    id: "demo-iot-traceability-2022",
    title: "Internet of Things applications for food traceability",
    authors: ["J. Li", "Y. Wang", "S. Chen"],
    year: 2022,
    source: "Demo catalog",
    publicationType: "Journal article",
    abstract: "An overview of sensor networks and connected platforms used to monitor food products from farm to consumer.",
    url: "https://example.org/demo/iot-food-traceability",
  },
  {
    id: "demo-agri-data-2021",
    title: "Data governance in digital agriculture: Opportunities and risks",
    authors: ["K. Klerkx", "E. Jakku", "P. Labarthe"],
    year: 2021,
    source: "Demo catalog",
    publicationType: "Conference paper",
    abstract: "The paper discusses ownership, access, interoperability, and responsible use of data in digital agriculture ecosystems.",
    doi: "10.1145/0000000.0000001",
  },
  {
    id: "demo-farm-ledger-2020",
    title: "A distributed ledger architecture for agricultural provenance",
    authors: ["L. Zhang", "H. Xu"],
    year: 2020,
    source: "Demo catalog",
    publicationType: "Conference paper",
    abstract: "A reference architecture for recording provenance events and validating product history across multiple organizations.",
    url: "https://example.org/demo/agricultural-provenance",
  },
  {
    id: "demo-rural-digital-2019",
    title: "Digital transformation and resilience in rural food systems",
    authors: ["S. Trendov", "S. Varas", "M. Zeng"],
    year: 2019,
    source: "Demo catalog",
    publicationType: "Report",
    abstract: "A discussion of digital technologies that can support resilient and inclusive rural food systems.",
  },
];
