import sys
import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, JSON, Text
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

try:
    from backend.database import Base
except ImportError:
    from database import Base

if "backend.models.agent_proposal" in sys.modules and __name__ == "models.agent_proposal":
    AgentProposal = sys.modules["backend.models.agent_proposal"].AgentProposal
elif "models.agent_proposal" in sys.modules and __name__ == "backend.models.agent_proposal":
    AgentProposal = sys.modules["models.agent_proposal"].AgentProposal
else:
    class AgentProposal(Base):
        """Diff-based proposal generated by an agent job.

        Contains operations (insert/replace/delete) with source references
        and conflict detection via base_version + base_hash.
        """
        __tablename__ = "agent_proposals"
        __table_args__ = {"extend_existing": True}

        id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
        job_id = Column(String, ForeignKey("agent_jobs.id"), nullable=False, index=True)

        base_version = Column(Integer, nullable=False)
        base_hash = Column(String, nullable=False)
        target_type = Column(String, nullable=False)  # "document" | "outline" | "selected_papers"
        target_section_id = Column(String, nullable=True)

        operations = Column(JSON, nullable=False)
        # List of: {
        #   operation_id: str, type: "replace"|"insert"|"delete"|"outline_patch"|"select_source",
        #   start: int, end: int, before: str, after: str,
        #   source_refs: [str], status: "pending"|"accepted"|"rejected"
        # }
        warnings = Column(JSON, nullable=True)

        tracked_html = Column(Text, nullable=True)
        summary = Column(JSON, nullable=True)

        status = Column(String, nullable=False, default="pending")
        # "pending" | "partially_accepted" | "accepted" | "rejected" | "applied" | "conflict"

        created_at = Column(
            DateTime(timezone=True),
            default=lambda: datetime.now(timezone.utc),
            server_default=func.now(),
        )
        decided_at = Column(DateTime(timezone=True), nullable=True)
        applied_at = Column(DateTime(timezone=True), nullable=True)

        job = relationship("AgentJob", back_populates="proposals")
        decisions = relationship(
            "AgentDecision",
            back_populates="proposal",
            cascade="all, delete-orphan",
            lazy="selectin",
        )
