from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field


class PaperSource(str, Enum):
    SEMANTIC_SCHOLAR = "semantic_scholar"
    ARXIV = "arxiv"
    OPENALEX = "openalex"


class AuthorSchema(BaseModel):
    name: str = Field(..., description="Full name of the author")
    author_id: Optional[str] = Field(None, description="External author ID if available")
    affiliations: Optional[List[str]] = Field(default_factory=list, description="List of affiliations")


class PaperSchema(BaseModel):
    id: str = Field(..., description="Unique internal paper ID or source_id")
    source: PaperSource = Field(..., description="API source of the paper metadata")
    external_id: str = Field(..., description="ID assigned by external source API")
    title: str = Field(..., description="Title of the paper")
    authors: List[AuthorSchema] = Field(default_factory=list, description="List of authors")
    year: Optional[int] = Field(None, description="Year of publication")
    venue: Optional[str] = Field(None, description="Journal or conference venue name")
    abstract: Optional[str] = Field(None, description="Abstract of the paper")
    doi: Optional[str] = Field(None, description="Digital Object Identifier (DOI)")
    url: Optional[str] = Field(None, description="Direct URL to paper webpage")
    citation_count: Optional[int] = Field(0, description="Total number of citations")
    summary_vi: Optional[str] = Field(None, description="Vietnamese summary generated by LLM")
    relevance_score: Optional[float] = Field(None, description="Relevance score (0.0 to 1.0)")


class SearchRequestSchema(BaseModel):
    query: str = Field(..., description="Search keywords query string")
    limit: int = Field(10, ge=1, le=50, description="Maximum number of results to fetch per source")
    sources: Optional[List[PaperSource]] = Field(
        default=[PaperSource.SEMANTIC_SCHOLAR, PaperSource.ARXIV, PaperSource.OPENALEX],
        description="Target search API sources"
    )


class SearchResponseSchema(BaseModel):
    query: str = Field(..., description="Original search query")
    total_results: int = Field(..., description="Total aggregated papers returned")
    papers: List[PaperSchema] = Field(default_factory=list, description="List of standardized paper objects")
